name: Build a firmware on demand

on:
  workflow_dispatch:
    inputs:
      keyboard:
        description: 'Keyboard'
        required: true
        type: choice
        options:
        - keyball61
      keymap:
        description: 'Keymap'
        required: true
        type: string
        default: 'via2'

jobs:

  build:

    uses: ./.github/workflows/build-firmware.yml
    with:
      qmk_version: '0.22.14'
      keyboard:    ${{ inputs.keyboard }}
      keymap:      ${{ inputs.keymap }}
